title: "Terraform OCI Container Engine for Kubernetes (aka OCI OKE) with Native POD networking"
description: "FoggyKitchen.com - Terraform OCI Container Engine for Kubernetes (aka OCI OKE) with Native POD networking."
stackDescription: "FoggyKitchen.com - Terraform OCI Container Engine for Kubernetes (aka OCI OKE) with Native POD networking."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - instance_os
  - linux_os_version
  - oci_service_gateway
  - network_cidrs

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name
  - node_pool_size
  - show_advanced 

- title: "OKE Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - kubernetes_version
  - ssh_public_key
  - shape
  - flex_shape_memory
  - flex_shape_ocpus
  - cluster_name
  - max_pods_per_node
  - deploy_ngnix
  - number_of_ngnix_replicas

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your Webserver"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain"
    description: "Choose Availability Domain where K8S Nodes will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  node_pool_size:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 3
    title: "How many K8S Nodes?"
    description: "Choose number of K8S Nodes to be deployed."

  # Optional Configuration

  kubernetes_version:
    type: enum
    title: "K8S Version"
    description: "Choose Kubernetes (K8S) version for OKE"
    default: "v1.23.4"
    required: false
    enum: 
      - "v1.23.4"
      - "v1.22.5"
      - "v1.20.11"
      - "v1.20.8"

  max_pods_per_node:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "What is maximum number of PODs per K8S Node?"
    description: "Choose number of K8S PODs to be deployed at maximum in one K8S Node."

  shape:
    type: oci:core:instanceshape:name
    title: "K8S Nodes Shape"
    description: "Choose a shape for your K8S nodes"
    default: "VM.Standard.E4.Flex"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "K8S Nodes Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - shape 
            - "VM.Optimized3.Flex"

  flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 16
    title: "K8S Nodes Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - shape
            - "VM.Standard.E4.Flex"
          - eq:
            - shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - shape 
            - "VM.Optimized3.Flex"

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  cluster_name:
    type: string
    title: "K8S Cluster Name"
    description: "Choose K8S Cluster Name"
    required: false

  instance_os:
    type: enum
    required: false
    visible: true
    title: "Instance OS"
    description: "Choose Operating System that determines the operating system for Webserver host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: true
    title: "Instance OS version"
    description: "Choose Operating System version that determines the operating system version for Webserver host."
    default: "7.9"
    enum:
      - "7.9"  

  deploy_ngnix:
    type: boolean
    title: "Deploy NGNIX?"
    description: "Check if you want to deploy NGNIX automatically."
    visible: true
    default: false

  number_of_ngnix_replicas:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "How many NGNIX replicas?"
    description: "Choose number of NGNIX replicas to be deployed."
    visible: 
      and:
        - deploy_ngnix

outputs:

  cluster_instruction:
    title: "Post deployment instructions"
    displayText: "Post deployment instructions."
    type: string
    visible: true
  



